cqrsnu-tutorial/Cafe/WebFrontend/Models/CloseModel.cs
namespace WebFrontend.Models
{
    public class CloseModel
    {
        public int Id { get; set; }
        public decimal AmountPaid { get; set; }
    }
}

cqrsnu-tutorial/Cafe/WebFrontend/Models/OrderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebFrontend.Models
{
    public class OrderModel
    {
        public class OrderItem
        {
            public int MenuNumber { get; set; }
            public string Description { get; set; }
            public int NumberToOrder { get; set; }
        }

        public List<OrderItem> Items { get; set; }
    }
}

cqrsnu-tutorial/Cafe/WebFrontend/Controllers/ChefController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using Cafe.Domain.Events;
using WebFrontend.ActionFilters;

namespace WebFrontend.Controllers
{
    [IncludeLayoutData]
    public class ChefController : Controller
    {
        public ActionResult Index()
        {
            return View(Domain.ChefTodoListQueries.GetTodoList());
        }

        public ActionResult MarkPrepared(Guid id, FormCollection form)
        {
            Domain.Dispatcher.SendCommand(new MarkFoodPrepared
            {
                Id = id,
                MenuNumbers = (from entry in form.Keys.Cast<string>()
                               where form[entry] != "false"
                               let m = Regex.Match(entry, @"prepared_\d+_(\d+)")
                               where m.Success
                               select int.Parse(m.Groups[1].Value)
                              ).ToList()
            });

            return RedirectToAction("Index");
        }
    }
}

cqrsnu-tutorial/Cafe/WebFrontend/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFrontend.ActionFilters;

namespace WebFrontend.Controllers
{
    [IncludeLayoutData]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

cqrsnu-tutorial/Cafe/WebFrontend/Controllers/TabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFrontend.ActionFilters;
using WebFrontend.Models;
using System.Text.RegularExpressions;
using Cafe.Domain.Commands;
using Cafe.Domain.Events;

namespace WebFrontend.Controllers
{
    [IncludeLayoutData]
    public class TabController : Controller
    {
        public ActionResult Open()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Open(OpenTab cmd)
        {
            cmd.Id = Guid.NewGuid();
            Domain.Dispatcher.SendCommand(cmd);
            return RedirectToAction("Order", new { id = cmd.TableNumber });
        }
        
        public ActionResult Close(int id) {
            return View(new CloseModel 
            {
                Id = id
            });
        }

        [HttpPost]
        public ActionResult Close(CloseModel model) {
            Domain.Dispatcher.SendCommand(new CloseTab {
                 Id = Domain.OpenTabQueries.TabIdForTable(model.Id),
                 AmountPaid = model.AmountPaid
            });
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Status(int id)
        {
            return View(Domain.OpenTabQueries.TabForTable(id));
        }

        public ActionResult Order(int id)
        {
            return View(new OrderModel
            {
                Items = (from item in StaticData.Menu
                         select new OrderModel.OrderItem
                         {
                             MenuNumber = item.MenuNumber,
                             Description = item.Description,
                             NumberToOrder = 0
                         }).ToList(),
            });
        }

        [HttpPost]
        public ActionResult Order(int id, OrderModel order)
        {
            var items = new List<OrderedItem>();
            var menuLookup = StaticData.Menu.ToDictionary(k => k.MenuNumber, v => v);
            foreach (var item in order.Items)
                for (int i = 0; i < item.NumberToOrder; i++)
                    items.Add(new OrderedItem
                    {
                        MenuNumber = item.MenuNumber,
                        Description = menuLookup[item.MenuNumber].Description,
                        Price = menuLookup[item.MenuNumber].Price,
                        IsDrink = menuLookup[item.MenuNumber].IsDrink
                    });
            
            Domain.Dispatcher.SendCommand(new PlaceOrder
            {
                Id = Domain.OpenTabQueries.TabIdForTable(id),
                Items = items
            });

            return RedirectToAction("Status", new { id = id });
        }


        public ActionResult MarkServed(int id, FormCollection form)
        {
            var tabId = Domain.OpenTabQueries.TabIdForTable(id);
            var menuNumbers = (from entry in form.Keys.Cast<string>()
                               where form[entry] != "false"
                               let m = Regex.Match(entry, @"served_\d+_(\d+)")
                               where m.Success
                               select int.Parse(m.Groups[1].Value)
                              ).ToList();

            var menuLookup = StaticData.Menu.ToDictionary(k => k.MenuNumber, v => v);
            
            var drinks = menuNumbers.Where(n => menuLookup[n].IsDrink).ToList();
            if (drinks.Any())
                Domain.Dispatcher.SendCommand(new MarkDrinksToServe
                {
                    Id = tabId,
                    MenuNumbers = drinks
                });

            var food = menuNumbers.Where(n => !menuLookup[n].IsDrink).ToList();
            if (food.Any())
                Domain.Dispatcher.SendCommand(new MarkFoodServed
                {
                    Id = tabId,
                    MenuNumbers = food
                });

            return RedirectToAction("Status", new { id = id });
        }

    }
}

cqrsnu-tutorial/Cafe/WebFrontend/Controllers/WaitStaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFrontend.ActionFilters;

namespace WebFrontend.Controllers
{
    [IncludeLayoutData]
    public class WaitStaffController : Controller
    {
        public ActionResult Todo(string id)
        {
            ViewBag.Waiter = id;
            return View(Domain.OpenTabQueries.TodoListForWaiter(id));
        }
    }
}

cqrsnu-tutorial/Cafe/WebFrontend/Views/Chef/Index.cshtml
@model List<Cafe.ReadModel.ChefTodoList.TodoListGroup>

@{
    ViewBag.Title = "Chef Todo List";
}

<h2>Meals To Prepare</h2>

@foreach (var group in Model)
{
    var i = 0;
    using (Html.BeginForm("MarkPrepared", "Chef"))
    {
        @Html.Hidden("id", group.Tab)
        <table class="table">
          <thead>
            <tr>
              <th>Menu #</th>
              <th>Description</th>
              <th>Prepared</th>
            </tr>
          </thead>
          <tbody>
            @foreach (var item in group.Items)
            {
                <tr>
                  <td>@item.MenuNumber</td>
                  <td>@item.Description</td>
                  <td>@Html.CheckBox(string.Format("prepared_{0}_{1}", i++, item.MenuNumber.ToString()))</td>
                </tr>
            }
          </tbody>
        </table>
        
        <button type="submit" class="btn">Mark Prepared</button>
        <hr />
    }
}

cqrsnu-tutorial/Cafe/WebFrontend/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Cafe Sample Application";
}

<h2>What do you want to do?</h2>

cqrsnu-tutorial/Cafe/WebFrontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap.min.css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @@media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Edument Cafe Sample App</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li>@Html.ActionLink("Home", "Index", "Home")</li>
              <li>@Html.ActionLink("Open Tab", "Open", "Tab")</li>
              <li>@Html.ActionLink("Chef Todo List", "Index", "Chef")</li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Wait Staff Todo Lists</li>
              @foreach (var w in ViewBag.WaitStaff as List<string>)
              {
              <li>@Html.ActionLink(w, "Todo", "WaitStaff", new { id = w }, null)</li>
              }
              <li class="nav-header">Open Tabs</li>
              @foreach (var t in ViewBag.ActiveTables as List<int>)
              {
              <li>@Html.ActionLink(t.ToString(), "Status", "Tab", new { id = t }, null)</li>
              }
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          @RenderBody()
        </div><!--/span-->
      </div><!--/row-->

      <hr>
      <footer>
        <p>&copy; Edument 2013</p>
      </footer>
    </div><!--/.fluid-container-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
</body>
</html>

cqrsnu-tutorial/Cafe/WebFrontend/Views/Tab/Close.cshtml
@model WebFrontend.Models.CloseModel

@{
    ViewBag.Title = "Close";
}

<h2>Close Tab</h2>

@using (Html.BeginForm()) {
    @Html.HiddenFor(m => m.Id)
    <fieldset>
        <label>Amount Paid</label>
        @Html.TextBoxFor(m => m.AmountPaid)

        <br>
        <button type="submit" class="btn">Close Tab</button>
    </fieldset>
}

cqrsnu-tutorial/Cafe/WebFrontend/Views/Tab/Open.cshtml
@model Cafe.Domain.Commands.OpenTab

@{
    ViewBag.Title = "Open Tab";
}

<h2>Open Tab</h2>

@using (Html.BeginForm())
{
  <fieldset>
    <label>Table Number</label>
    @Html.TextBoxFor(m => m.TableNumber)
   
    <label>
      Waiter/Waitress
    </label>
    @Html.DropDownListFor(m => m.Waiter, (ViewBag.WaitStaff as List<string>)
        .Select(w => new SelectListItem { Text = w, Value = w }))
    <br>

    <button type="submit" class="btn">Open Tab</button>
  </fieldset>
}

cqrsnu-tutorial/Cafe/WebFrontend/Views/Tab/Order.cshtml
@model WebFrontend.Models.OrderModel

@{
    ViewBag.Title = "Place Order";
}

<h2>Place Order</h2>

@using (Html.BeginForm())
{
  <fieldset>
    <table class="table">
      <thead>
        <tr>
          <td>Menu #</td>
          <td>Description</td>
          <td>Number To Order</td>
        </tr>
      </thead>
      <tbody>
        @for (int i = 0; i < Model.Items.Count; i++)
        {
            <tr>
              <td>
                @Model.Items[i].MenuNumber
                @Html.HiddenFor(m => m.Items[i].MenuNumber)
              </td>
              <td>@Model.Items[i].Description</td>
              <td>@Html.TextBoxFor(m => m.Items[i].NumberToOrder)</td>
            </tr>
        }
      </tbody>
    </table>

    <button type="submit" class="btn">Place Order</button>
  </fieldset>
}

cqrsnu-tutorial/Cafe/WebFrontend/Views/Tab/Status.cshtml
@model Cafe.ReadModel.OpenTabs.TabStatus

@{
    ViewBag.Title = "Tab Status";
}

<h2>Tab For Table @Model.TableNumber</h2>

<div>
    <i class="icon-remove"></i>
    @Html.ActionLink("Close Table", "Close", new { id = Model.TableNumber })
</div>
<div>
  <i class="icon-plus"></i>
  @Html.ActionLink("Order Food/Drink", "Order", new { id = Model.TableNumber })
</div>

@if (Model.ToServe.Any())
{
    using (Html.BeginForm("MarkServed", "Tab", new { id = Model.TableNumber }))
    {
        var i = 0;
        <h3>Items To Serve</h3>
        <table class="table">
          <thead>
            <tr>
              <td>Menu #</td>
              <td>Description</td>
              <td>Mark Served</td>
            </tr>
          </thead>
          <tbody>
            @foreach (var item in Model.ToServe)
            {
                <tr>
                  <td>@item.MenuNumber</td>
                  <td>@item.Description</td>
                  <td>@Html.CheckBox(string.Format("served_{0}_{1}", i++, item.MenuNumber.ToString()))</td>
                </tr>
            }
          </tbody>
        </table>
    
        <button type="submit" class="btn">Mark Served</button>
    }
}

@if (Model.InPreparation.Any())
{
    <h3>Food In Preparation</h3>
    <table class="table">
      <thead>
        <tr>
          <td>Menu #</td>
          <td>Description</td>
        </tr>
      </thead>
      <tbody>
        @foreach (var item in Model.InPreparation)
        {
            <tr>
              <td>@item.MenuNumber</td>
              <td>@item.Description</td>
            </tr>
        }
      </tbody>
    </table>
}

@if (Model.Served.Any())
{
    <h3>Items Already Served</h3>
    <table class="table">
      <thead>
        <tr>
          <td>Menu #</td>
          <td>Description</td>
        </tr>
      </thead>
      <tbody>
        @foreach (var item in Model.Served)
        {
            <tr>
              <td>@item.MenuNumber</td>
              <td>@item.Description</td>
            </tr>
        }
      </tbody>
    </table>
}

cqrsnu-tutorial/Cafe/WebFrontend/Views/WaitStaff/Todo.cshtml
@model Dictionary<int, List<Cafe.ReadModel.OpenTabs.TabItem>>

@{
    ViewBag.Title = "Todo List For " + ViewBag.Waiter;
}

<h2>Todo List For @ViewBag.Waiter</h2>

@foreach (var table in Model)
{
    <h3>Table @table.Key</h3>
    
    <table class="table">
      <thead>
        <tr>
          <th>Menu #</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        @foreach (var item in table.Value)
        {
            <tr>
              <td>@item.MenuNumber</td>
              <td>@item.Description</td>
            </tr>
        }
      </tbody>
    </table>
    
    @Html.ActionLink("Go To Tab", "Status", "Tab", new { id = table.Key }, null)
}